In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.svm import SVC
#from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/Co2_CO_data.csv')
df.head()

entry_id  Temp  Humid    Co2_PPM    CO_PPM
0         1  33.5   78.5  403.11276  12.67842
1         2  33.5   78.1  417.96375  10.16066
2         3  33.4   78.2  430.89926   8.66857
3         4  33.4   78.4  447.28165   8.86928
4         5  33.4   78.4  477.25467   7.90476

In [ ]:
df.insert(5,'Air_Quality',0)
df.head()

entry_id  Temp  Humid    Co2_PPM    CO_PPM  Air_Quality
0         1  33.5   78.5  403.11276  12.67842            0
1         2  33.5   78.1  417.96375  10.16066            0
2         3  33.4   78.2  430.89926   8.66857            0
3         4  33.4   78.4  447.28165   8.86928            0
4         5  33.4   78.4  477.25467   7.90476            0

In [ ]:
co = df['CO_PPM']
co2 = df['Co2_PPM']

In [ ]:
for i in range(len(co2)):
  if (co[i] < 1.5 or co2[i] < 450):
    df.loc[i,'Air_Quality']= 0
  if (co[i] > 3 and co[i] < 5) or (co2[i] > 600 and co2[i] < 800):
    df.loc[i,'Air_Quality'] = 1
  if  (co[i] > 5 and co[i] < 8) or (co2[i] > 800 and co2[i] < 1200):
    df.loc[i,'Air_Quality'] = 2
  if  (co[i] > 8 and co[i] < 15) or (co2[i] > 1200 and co2[i] < 1500):
    df.loc[i,'Air_Quality'] = 3
  if (co[i] > 15):
    df.loc[i,'Air_Quality'] = 4

In [ ]:
df.head(50)

entry_id  Temp  Humid     Co2_PPM     CO_PPM  Air_Quality
0          1  33.5   78.5   403.11276   12.67842            3
1          2  33.5   78.1   417.96375   10.16066            3
2          3  33.4   78.2   430.89926    8.66857            3
3          4  33.4   78.4   447.28165    8.86928            3
4          5  33.4   78.4   477.25467    7.90476            2
5          6  33.5   78.3   444.91388    5.67272            2
6          7  33.4   78.2   439.42444    5.14585            2
7          8  33.4   78.2   417.21176    4.77915            1
8          9  33.4   78.4   419.47055    4.32571            1
9         10  33.4   78.6   427.82959    3.52982            1
10        11  33.4   78.6   424.77585    4.54752            1
11        12  33.4   78.4   424.01505    3.01965            1
12        13  33.4   78.4   420.22546    3.09993            1
13        14  33.3   78.7   418.71661    2.71633            0
14        15  33.3   79.1   417.21176    3.09993            1
15        16  33.3   79.1   417.21176    2.37470            0
16        17  33.2   79.3   415.71100    2.31105            0
17        18  33.2   79.3   416.46094    2.12893            0
18        19  33.2   79.3   421.73828    2.43986            0
19        20  33.2   79.3   414.21399    2.37470            0
20        21  33.2   79.3   412.72101    2.07106            0
21        22  33.2   79.3   415.71100    1.90559            0
22        23  33.2   79.3   408.26590    2.24889            0
23        24  33.2   79.3   434.75916    1.03568            0
24        25  33.3   79.2   409.74698    1.90559            0
25        26  33.4   79.1   405.31531    1.47610            0
26        27  33.4   79.1   401.64917    1.56345            0
27        28  33.4   79.4   406.78860    1.35302            0
28        29  33.4   79.1   398.73395    1.35302            0
29        30  33.4   78.9   398.00732    1.35302            0
30        31  33.4   78.9   448.86539    1.43403            0
31        32  33.4   78.7   400.18970    1.39302            0
32        33  33.4   78.6   393.66919    1.20286            0
33        34  33.4   78.6   482.25101   19.79050            4
34        35  33.4   78.9   653.09064  172.41882            4
35        36  33.5   78.8  1036.22559   68.13527            4
36        37  33.7   78.1  1263.97852   97.76582            4
37        38  33.7   77.8  1496.74963  515.09271            4
38        39  33.9   77.7  1587.48376  245.13216            4
39        40  34.0   77.3  1506.62622  719.27930            4
40        41  34.3   75.9  1404.46777   91.38332            4
41        42  34.4   75.7  1406.34375  324.14090            4
42        43  34.5   75.4  1387.66809  201.30717            4
43        44  34.5   74.9  1323.81165   66.94566            4
44        45  34.5   74.8  1288.35657   48.41780            4
45        46  34.4   74.6  1120.33948   19.38629            4
46        47  34.2   75.1  1054.15076   10.86562            3
47        48  34.0   75.6  1030.30212    9.49587            3
48        49  33.9   76.1   985.26978    6.55100            2
49        50  33.8   76.2   948.67047    4.43541            2

In [ ]:
X = df[['CO_PPM', 'Co2_PPM']]
y = df['Air_Quality']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=42)

In [ ]:
model = LogisticRegression(multi_class='multinomial', solver='newton-cg', C=1.0)
#model = RandomForestClassifier(n_estimators=100, random_state=50)
#model = SVC(kernel='rbf', C=1.0, gamma='scale')
#model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='multinomial', solver='newton-cg')

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 3, 0, 0, 0, 0, 1, 0, 3, 0, 2, 4, 2, 4, 2, 4, 1, 1, 2, 4, 1, 1,
       1, 3, 4, 1, 4, 2, 0, 4, 2, 2, 1, 2, 2, 0, 3, 0, 4, 0, 1, 3, 0, 4,
       1, 1, 1, 4, 1, 2, 3, 2, 0, 0, 4, 0, 2, 0, 4, 1, 2, 0, 0, 1, 2, 1,
       1, 4, 0, 3, 2, 0, 3])

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8767123287671232

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[18,  1,  0,  0,  0],
       [ 2, 13,  2,  0,  0],
       [ 0,  3, 13,  1,  0],
       [ 0,  0,  0,  7,  0],
       [ 0,  0,  0,  0, 13]])

In [ ]:
model.coef_

array([[-2.11130717, -0.02267492],
       [-0.90566874, -0.00308743],
       [ 0.13311002,  0.0097678 ],
       [ 1.15271109,  0.00769154],
       [ 1.73115465,  0.00830161]])

In [ ]:
np.hstack(model.intercept_)

array([ 21.84339371,   9.70670356,  -2.92515529,  -9.55599913,
       -19.06894285])